# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 711c13570f7bf510be9f01c66031170e3eda7b8cfe208f05b9d4dc12d9996c851a5587a49197616d40904f425123aa4bf3160ee145970058d27163c758e5fed3

test:
  secret_key_base: d118f463e91cff9c85d5710588af0121f86dcbbc7475bef93267c3d8d6fb349aaf1d30438028ecf7c8329eb70c64dcb27e21c9c489a9b5f67dd1ef2b9386cd75

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
